name: 'BukkitHelper'
author: 'zhufucdev'
main: 'com.zhufucdev.bukkit_helper.MainPlugin'
description: 'A bridge between bukkit server and Android devices.'
version: 'Alpha 0.1'
api-version: '1.16'

commands:
  keyring:
    description: 'Manage keyring via which Android is connected.'
    permission: 'helper.keyring'
    usage: |
      /<command> add <name> <key>
      /<command> remove <name>
      /<command> list
  server:
    description: 'Manage the server side.'
    permission: 'helper.server'
    usage: |
      /<command> start
      /<command> stop
      /<command> restart
      /<command> settings <name> [new value]

permissions:
  helper.keyring:
    description: 'Allows you to manage the keyring of server.'
    default: 'op'
  helper.server:
    description: 'Allows you to manage the server.'
    default: 'op'